id: I5B470EDE
legacy_id: P002980
ocr_import_info:
  bdrc_scan_id: W8LS19924
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T14:22:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:36:43.343085+00:00'
last_modified: 2022-09-04 12:36:48.987581
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS19924
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS19924
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་ཁྲིད་ཡིག་ཟབ་དོན་འཐོར་བསྡུས་ཀུན་བཟང་བླ་མའི་ཞལ་རྒྱུན་བདུད་རྩིའི་བུམ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.5526092437401163
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I8LS19926:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS19926
      total_pages: 80
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS19926.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5526092437401163
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
